### ISSUE TITLE
open job menu after a revive

### ISSUE THREAD

**Issue by Jhudri** [EbenSantuy/esx_kashacter-TUTORIAL-FIXED-ALL-ISSUE#1]
I cant seem to open job menu after a revive.

**Comment by EbenSantuy** [comment]
try my esx_ambulance

**Comment by Jhudri** [comment]
I got it to work by removing isDead in the menu in police and mechanic and using your ambulance job...

**Comment by EbenSantuy** [comment]
> I cant seem to open job menu after a revive.



> I got it to work by removing isDead in the menu in police and mechanic and using your ambulance job...

for anyone who can't open the job menu after die ! try to go down to the client/main.lua
